//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project4Aptech.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public int id { get; set; }
        public string Num_id { get; set; }
        public string Usn { get; set; }
        public string Pwd { get; set; }
        public Nullable<int> A_Status { get; set; }
    
        public virtual Customers Customers { get; set; }
    }
}
