//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project4Aptech.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Customers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customers()
        {
            this.Account = new HashSet<Account>();
        }
    
        public string Id { get; set; }
        public string Name { get; set; }
        [StringLength(10, ErrorMessage = "Phone number is not valid")]

        [DataType(DataType.PhoneNumber, ErrorMessage = "Phone number is not valid")]
        
        public string PhoneNumber { get; set; }
        public string Address { get; set; }
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> DOF { get; set; }
        public string acc_num { get; set; }
        [DataType(DataType.Currency)]
        public Nullable<double> balance { get; set; }
        [DataType(DataType.EmailAddress, ErrorMessage = "Email is not valid format")]
        public string email { get; set; }
        public string Cs_status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Account> Account { get; set; }
    }
}
