//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project4Aptech.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Users
    {
        public int id { get; set; }
        [StringLength(1000, MinimumLength = 6, ErrorMessage = "Password must be atleast 6 characters")]
        public string Password { get; set; }
        public string UserName { get; set; }
        public Nullable<int> Roll_id { get; set; }
    
        public virtual Roles Roles { get; set; }
    }
}
